routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DefaultController@index')->name('index');
Route::get('/products', 'ProductController@index')->name('product.index');
Route::get('/product/{id}', 'ProductController@show')->name('product.show');

Route::get('/solutions', 'SolutionController@index')->name('solution.index');
Route::get('/solution/{id}', 'SolutionController@show')->name('solution.show');

Route::get('/news', 'NewsController@index')->name('news.index');
Route::get('/news/{id}', 'NewsController@show')->name('news.show');

Route::get('/news', 'NewsController@index')->name('news.index');

Route::get('/pages/{slug}', 'PagesController@show')->name('pages.show');


Route::post('/request', 'RequestController@submit')->name('request.post');


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

app/Banner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Banner extends Model
{
    //
}

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    //
    public function getCreatedDateAttribute()
	{
		$date = $this->attributes['created_at'];
		$time = strtotime($date);
		return date('d.m.Y');
	}
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
}

app/Request.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Request extends Model
{
    //
}

app/Solution.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Solution extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends \TCG\Voyager\Models\User
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DefaultController.php
<?php 
namespace App\Http\Controllers;

use App\Solution;
use App\Product;
use App\Banner;
/**
 * 
 */
class DefaultController extends Controller
{
	public function index()
	{
        $solution = Solution::latest()->take(1)->first();
        $products = Product::latest()->take(5)->get();
        $banners = Banner::latest()->take(4)->get();

		return view('main',
			compact('solution', 'products', 'banners'));
	}
}

app/Http/Controllers/NewsController.php
<?php 
namespace App\Http\Controllers;

use App\News;

/**
 * 
 */
class NewsController extends Controller
{
	public function index()
	{
		$list = News::all();
		return view('news.index', compact('list'));
	}

	public function show($id)
	{
		$list = News::all();
		$entity = News::find($id);
		if (!$entity) {
			die(404);
		}
		return view('news.show', compact('entity', 'list'));
	}
}

app/Http/Controllers/PagesController.php
<?php 
namespace App\Http\Controllers;

use TCG\Voyager\Models\Page;

/**
 * 
 */
class PagesController extends Controller
{
	public function show($slug)
	{
		$list = Page::all();
		$entity = Page::where('slug', $slug)->first();
		if (!$entity) {
			die(404);
		}
		return view('pages.page', compact('entity', 'list'));
	}
}

app/Http/Controllers/ProductController.php
<?php 
namespace App\Http\Controllers;

use App\Product;

/**
 * 
 */
class ProductController extends Controller
{
	public function index()
	{
		$list = Product::all();
		return view('products.index', compact('list'));
	}

	public function show($id)
	{
		$list = Product::all();
		$entity = Product::find($id);
		if (!$entity) {
			die(404);
		}
		return view('products.show', compact('entity', 'list'));
	}
}

app/Http/Controllers/RequestController.php
<?php 
namespace App\Http\Controllers;

use App\Request as Feedback;
use Illuminate\Support\Facades\Mail;
use App\Mail\FeedbackSent;


use Illuminate\Http\Request;

/**
 * 
 */
class RequestController extends Controller
{
	public function submit(Request $request)
	{
		$record = new Feedback;
		$record->name = $request->input('name');
		$record->phone = $request->input('phone');
		$record->email = $request->input('email');
		$record->phone = $request->input('phone');
		$record->body = $request->input('body');
		$record->company = $request->input('company');
		$record->request_url = $request->input('request_url');

		$record->save();

		Mail::to(['abylay@logistic-systems.kz', 'salamat@e-drivetech.kz'])
			->send(new FeedbackSent($record));

		header('Location: ' . $record->request_url . '?feedback=success');
	}
}

app/Http/Controllers/SolutionController.php
<?php 
namespace App\Http\Controllers;

use App\Solution;

/**
 * 
 */
class SolutionController extends Controller
{
	public function index()
	{
		$list = Solution::all();
		return view('solutions.index', compact('list'));
	}

	public function show($id)
	{
		$list = Solution::all();
		$entity = Solution::find($id);
		if (!$entity) {
			die(404);
		}
		return view('solutions.show', compact('entity', 'list'));
	}
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>

<?php 
	$separator = isset($title) ? ' | ' : '';
?>
<title>{{ ($title ?? '') . $separator . setting('site.meta_title') }}</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="{{ $description ?? setting('site.meta_description') }}" />
<meta name="keywords" content="{{ $keywords ?? '' }}" />


<link rel="shortcut icon" href="/old_static/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" type="text/css" href="/old_static/style.css" media="screen,projection,print" />

<link rel="stylesheet" type="text/css" href="/old_static/thickbox.css" />
<link rel="stylesheet" type="text/css" href="/old_static/print.css" media="print" />
<script type="text/javascript" src="/old_static/js.js"></script>
<script type="text/javascript" src="/old_static/jquery-1.3.min.js"></script>
<script type="text/javascript" src="/old_static/jquery.Thickbox.js"></script>
<script type="text/javascript" src="/old_static/slider.js"></script>
</head>
<body>

	<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(56624890, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        webvisor:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/56624890" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-154423628-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-154423628-1');
</script>


<div id="theboss" class="page"
>

	<a href="/" title="E-Drivetech Eurasia">
		<img src="/old_static/logo.jpg" class="logo" alt="E-Drivetech Eurasia" title="E-Drivetech Eurasia" />
	</a>
	
	
	<span class="slogan">
		<strong>{{ setting('site.title') }}</strong><br />
		{{ setting('site.description') }}
	</span>
	
	<div id="menu">
		
		<div ><a href="/products">Продукты EDT</a></div>
		<img class="marker" src="/old_static/marker.gif" alt="" />
		<div ><a href="/solutions">Решения</a></div>
		<img class="marker" src="/old_static/marker.gif" alt="" />
		<div ><a href="/news">Новости и события</a></div>
		<img class="marker" src="/old_static/marker.gif" alt="" />
		<div ><a href="/pages/podderjka">Поддержка</a></div>
		<img class="marker" src="/old_static/marker.gif" alt="" />
		<div ><a href="/pages/klienty">Наши клиенты</a></div>
		<img class="marker" src="/old_static/marker.gif" alt="" />
		<div ><a href="/pages/o-nas">О нас</a></div>
		<img class="marker" src="/old_static/marker.gif" alt="" />
		<div ><a href="/pages/kontakty">Контакты</a></div>
		<img class="marker" src="/old_static/marker.gif" alt="" />
	</div>
				

    @yield('content')
 
</div>

<div class="footertextin">
	<div class="quickbox">
		<h4>Продукты EDT</h4>
		@foreach ($productsInFooter as $product)
			<a href="/product/{{ $product->id }}">{{ $product->name }}</a><br />
		@endforeach
	</div>

	<div class="quickbox">
		<h4>Решения EDT</h4>
		@foreach ($solutionsInFooter as $solution)
			<a href="/solution/{{ $solution->id }}">{{ $solution->name }}</a><br />
		@endforeach
	</div>
	<div class="quickbox">
		<h4>О EDT</h4>
		@foreach ($pages as $page)
			<a href="/pages/{{ $page->slug }}">{{ $page->title }}</a><br />
		@endforeach
	</div>
</div>

<script src="https://unpkg.com/imask"></script>
<script>
	var element = document.getElementById('phoneMasked');
	var maskOptions = {
	  mask: '+{7}(000)000-00-00'
	};
	var mask = IMask(element, maskOptions);
</script>
			
</body>
</html>

resources/views/layouts/inner.blade.php
@extends('layouts.app', [
	'title' => $title ?? null,
	'description' => $description ?? null,
	'keywords' => $keywords ?? null,
	])

@section('content')


<div class="pixels"> 

<div id="leftcol">
	
	<div class="menulevel0">

		@yield('links')
	
	</div>
<h3 class="contacttitle">Задавайте вопросы</h3>
<form class="frame" action="/request" method="POST">

	@if (isset($_GET['feedback']) && $_GET['feedback'] == 'success')
		<h4 style="text-align: center; color: red">Ваше сообщение отправлено!</h4>
	@endif
	<div id="ContactForm" class="contact">
		<input onfocus="if (this.value==this.defaultValue) this.value='';" type="text" value="Имя" name="name" required>
		<input onfocus="if (this.value==this.defaultValue) this.value='';" value="E-mail" type="email" name="email">
		<input type="tel" name="phone" id="phoneMasked" placeholder="+7(___)___-__-__">
		<input id="hfld_Company" onfocus="if (this.value==this.defaultValue) this.value='';" value="Компания" type="text" name="company">
		
		<textarea id="hfld_Comments" onfocus="if (this.value==this.defaultValue) this.value='';" rows="2" cols="20" name="body">Сообщение</textarea>
		<button>Отправить</button>
		<!-- <button>Отправить</button> -->
		@csrf
		<input type="hidden" name="request_url" value="{{ url()->current() }}">
	</div>
</form>
<div class="contactend">
</div>


&nbsp;
</div>


@yield('main')


<div id="rightcol">
	
	&nbsp;
</div>


</div>
</div>

@endsection

resources/views/main.blade.php
@extends('layouts.app')

@section('content')

	<style>
		#slide > div {
			background-position: center center;
			background-repeat: no-repeat;
		}
	</style>
	<div class="sun">
	<div class="co_left">
	    
	    <div id="cont">
			
			<div id="slide">
				@foreach ($banners as $item)
					
					<div style="background-image: url({{ Voyager::image($item->image) }});">
						
						<span class="trans">
							<a href="{{ $item->link }}" >
								<img src="/old_static/arrow.png" alt /></a>
							<p>{{ $item->brief }}</p>
						</span>
					
					</div>
				@endforeach


			</div>
			
			<div class="bullets">
				@php
					$i = 0;
				@endphp

				@foreach ($banners as $item)
					<a href="javascript:goSlide({{ $i }})" class="bullet activo tab_{{ ($i+1) }}">
						<h2>{{ $item->name }}</h2>
					</a>
					@php
						$i++;
					@endphp
				@endforeach
				
			</div>
			
		</div>
		

		<div class="textcontent">
			<h1>{{ setting('main.infoblock_title') }}</h1>
			{!! setting('main.infoblock_body') !!}
		</div>
	</div>

	<div class="co_right">

		<div class="orangebox">
			<h3>Продукты EDT</h3>
			<div>
				@foreach ($products as $element)
					<a href="/product/{{ $element->id }}">{{ $element->name }}</a>
				@endforeach

			</div> 
			<a href="/products" class="all">Все продукты</a>
		</div>
		
		<div class="orangeboxright">
			<h3>Решение EDT</h3>
			<div>

				@if (isset($solution->image))
					<a href="/solution/{{ $solution->id }}">
						<img src="{{ Voyager::image($solution->image) }}">
					</a>
				@endif
				

			
			<a href="/solution/{{ $solution->id }}">
		
				<span class="title">{!! $solution->brief !!}</span>
			</a>
			

			</div>
			<a href="/products" class="all">Все решения</a>
		</div>
		
		
			<div class="feature" >
				
				<a href="/news" >
					
			<img src="/old_static/7643653849_Small.png" alt="Login Page" title="Login Page" />
		
				</a>
				
				<a href="/news" >Объявление о выпуске WFL 3.20</a>
				
		<div class="clear"></div>
	<p>Предлагаем ознакомиться с последним обновлением WorldFleetLog. <a href="/news">Последний релиз</a> включает в себя множество новых ориентированных на клиента функций</p>
			</div>


			<div class="feature" style='margin-right:0px;'>
				
				<a href="http://www.e-drivetech.com/products/wflmobile"  target='_blank' >
					
					<img src="/old_static/1795876927_Small.png" alt="WFLMobile" title="WFLMobile" />
		
				</a>
				
				<a href="http://www.e-drivetech.com/products/wflmobile"  target='_blank' >Приложение World Fleet</a>
				
		<div class="clear"></div>
	<p>Приложение EDT World Fleet обеспечивает мобильный доступ на ходу! Наш последний выпуск включает в себя новый интерфейс с расширенными функциями и отличным пользовательским интерфейсом. <a href="http://www.e-drivetech.com/products/wflmobile" target="_blank">Теперь <strong>поддерживает Push-уведомления</strong></a>.</p>
			</div>


			<div class="feature" >
				
				<a href="https://www.worldfleetlog.com/wfl/" >WorldFleetLog</a>
				
			<div class="clear"></div>
				<p>Авторизоваться в <a href="https://www.worldfleetlog.com/wfl/">WorldFleetLog.</a></p>
			</div>


			<div class="feature" style='margin-right:0px;'>
				
				<a href="/pages/podderjka" >
					
			<img src="/old_static/6535783140_Small.jpg" alt="EDT Customer Support" title="EDT Customer Support" />
		
				</a>
				
				<a href="/pages/podderjka" >Служба поддержки</a>
				
		<div class="clear"></div>
		<p>Свяжитесь с нами для технических запросов и запасных частей. Проверьте наши часто задаваемые вопросы, скачать калькулятор экономии затрат!</p>
		</div>


	</div>

	</div>
@endsection

resources/views/news/index.blade.php
@extends('layouts.inner')

@section('links')
	
	@foreach ($list as $item)
		<a href="/news/{{ $item->id }}">{{ $item->name }}</a>
	@endforeach

@endsection('links')

@section('main')

<div id="centercol">
	<div class="breadcrumbs"><a href='/EDT/index.asp'>Главная</a>&nbsp;&#187;&nbsp;Новости EDT</div>


	@foreach ($list as $item)

		<div class="news">

			<a href="/news/{{ $item->id }}">
				<h4>{{ $item->name }}</h4>
			</a>
			<span>{{ $item->created_date }}</span>
			{{ $item->brief }}
			
			<br />	
			<a href="/news/{{ $item->id }}">
				Далее...
			</a>
		</div>
		
	@endforeach

</div>
	
@endsection('main')

resources/views/news/show.blade.php
@extends('layouts.inner')

@section('links')

	@foreach ($list as $item)
		<a href="/news/{{ $item->id }}">{{ $item->name }}</a>
	@endforeach
	
@endsection('links')

@section('main')

<div id="centercolHide">
	<div class="breadcrumbs">
		<a href='/'>Главная</a>&nbsp;&#187;&nbsp;
		<a href='/news'>Новости EDT</a>&nbsp;&#187;&nbsp;
		{{ $entity->name }}
	</div>

	<h1>{{ $entity->name }}</h1>
	
	<div class="floatright space">
		<a href="{{ Voyager::image($entity->images) }}" target="_blank" class="thickbox">
			<img src="{{ Voyager::image($entity->images) }}" width="300"/>
		</a>
	</div>
	<h3>

	{!! $entity->body !!}

	<div class="clear"></div>

</div>

@endsection('main')

resources/views/pages/page.blade.php
@extends('layouts.inner', [
	'title' => $entity->title,
	'description' => $entity->meta_description,
	'keywords' => $entity->meta_keywords,
	])

@section('links')

	@foreach ($list as $item)
		<a href="/pages/{{ $item->slug }}">{{ $item->title }}</a>
	@endforeach
	
@endsection('links')

@section('main')

<div id="centercolHide">
	<div class="breadcrumbs">
		<a href='/'>Главная</a>&nbsp;&#187;&nbsp;
		<a href='/pages/o-nas'>О нас</a>&nbsp;&#187;&nbsp;
		{{ $entity->title }}
	</div>

	<h1>{{ $entity->title }}</h1>
	
	<div class="floatright space">
		<a href="{{ Voyager::image($entity->images) }}" target="_blank" class="thickbox">
			<img src="{{ Voyager::image($entity->images) }}" width="300"/>
		</a>
	</div>
	<h3>

	{!! $entity->body !!}

	<div class="clear"></div>

</div>

@endsection('main')

resources/views/products.blade.php
@extends('layouts.app')

@section('content')


<div class="pixels"> 

<div id="leftcol">
	
			<div class="menulevel0">

			<a href="http://www.e-drivetech.com/products/worldfleetlog"  target="_self" title="WorldFleetLog">WorldFleetLog</a>
			
			<a href="http://www.e-drivetech.com/products/F1-FMS"  target="_self" title="F1 FMS">F1 FMS</a>
			
			<a href="http://www.e-drivetech.com/products/RF-Sensors"  target="_self" title="RF Sensors">RF Сенсоры</a>
			
			<a href="http://www.e-drivetech.com/products/Digital-Video-Recorder"  target="_self" title="Mobile DVR and Dashcam Solutions">Мобильный DVR и решения видеорегистраторы</a>
			
			<a href="http://www.e-drivetech.com/products/SmartSight-S1-Dashcam"  target="_self" title="SmartSight S1 Dashcam">Ыидеорегистатор SmartSight S1</a>
			
			</div>
<script type="text/javascript"> 
$(document).ready(function() {
   $("#ContactSendBtn").click(function() {
		var _name = $("#hfld_Name").val()
		var _phone = $("#hfld_Phone").val()
		var _email = $("#hfld_Email").val()
		var _body = $("#hfld_Comments").val()
		var _company = $("#hfld_Company").val()
		
		var _Country = $("#hfld_Country").val()
		
		var _captch = $("#hfld_Captcha").val()
		var _captchError = $("#hfld_CaptchaError").val()
		var _successMsg	=$("#hfld_Success").val()
		if (_email.length == 0) {
			alert("You entered the wrong digits. Please try again.");
			return false;
		}
		$.post("/EDT/Templates/contact.asp", { name: _name,company: _company, email:_email, country:_Country,body:_body,captch:_captch,link:pageURL,Slink:strPageName  },
			function(data){
				if (data == "0") {
					$("#ContactResponseMsg").html("<span>"+ _captchError +"</span>");
				}else{
				$("#ContactResponseMsg").addClass("contact")
				$("#ContactForm").fadeOut("slow");
				$("#ContactSendBtn").fadeOut("slow");
				$("#ContactResponseMsg").html(_successMsg);
					_gaq.push(['_trackEvent', 'Fast_Contact', 'Thank_You', '', '']);
					setTimeout(function(){
				$("#hfld_Name").val("");
				$("#hfld_Phone").val("");
				$("#hfld_Email").val("");
				$("#hfld_Comments").val("");
				$("#hfld_Captcha").val("");
				$("#hfld_Company").val(""); 
					
					$("#hfld_Country").val(""); 
										  
				$("#ContactResponseMsg").removeClass("contact");
				$("#ContactForm").fadeIn("slow");
				$("#ContactSendBtn").fadeIn("slow");
				$("#ContactResponseMsg").html();
				}, 4000);
				}
		});
   });
 });
</script>
<h3 class="contacttitle">Задавайте вопросы</h3>
<div class="frame">
	<div id="ContactForm" class="contact">
		<input id="hfld_Name" onfocus="if (this.value==this.defaultValue) this.value='';" type="text" value="Имя" />
		<input id="hfld_Email" onfocus="if (this.value==this.defaultValue) this.value='';" value="E-mail" type="text" />
		<input id="hfld_Company" onfocus="if (this.value==this.defaultValue) this.value='';" value="Компания" type="text" />
		
		<textarea id="hfld_Comments" onfocus="if (this.value==this.defaultValue) this.value='';" rows="2" cols="20">Сообщение</textarea>
		<span class="long">Введите числа</span>
		<img id="ImgCaptcha" src="/EDT/Templates/forms/captcha.asp" alt="Введите цифры с картинки" />
		<input type="text" id="hfld_Captcha" />
		<input class="inputcolor3" id="ContactSendBtn" type="submit" name="Отправить"/>
		<!-- <button>Отправить</button> -->
	</div>
</div>
<div class="contactend">
	<input type="hidden" id="hfld_CaptchaError" value="Wrong numbers" />
	<input type="hidden" id="hfld_Success" value="Your message was sent successfully" />
</div>
<div id="ContactResponseMsg" class="contactend"></div>


&nbsp;
</div>


<div id="centercol">
<div class="breadcrumbs"><a href='/EDT/index.asp'>Главная</a>&nbsp;&#187;&nbsp;Продукты EDT</div>
<h1>Продукты EDT</h1>
<h2>Продукты и решения EDT обеспечивают превосходную производительность FMS ваших клиентов, подкрепленную непревзойденной поддержкой клиентов.</h2>


<div class="imglist">

	
	<a href="http://www.e-drivetech.com/products/worldfleetlog">
		<h4>WorldFleetLog</h4>
	</a>
	WorldFleetLog - это облачное приложение EDT для управления автопарком, предназначенное для отображения и управления данными, собранными из продуктов EDT для управления автопарком и топливом. С WorldFleetLog у менеджеров автопарков в распоряжении есть разнообразная информация для отслеживания транспортных средств в режиме реального времени, управления активами и мониторинга водителя.
	
	<br />	
	<a href="http://www.e-drivetech.com/products/worldfleetlog">
		Далее...
	</a>
</div>




<div class="imglist">

	
	<a href="http://www.e-drivetech.com/products/F1-FMS">
		<h4>F1 FMS</h4>
	</a>
	FMS F1 предназначена для приложений государственного, военного, коммерческого и частного секторов, которые требуют высокой производительности.
	<a href="http://www.e-drivetech.com/products/F1-FMS">
			<br />	Далее...
			</a>
</div>




<div class="imglist">

	
	<a href="http://www.e-drivetech.com/products/RF-Sensors">
		<h4>RF Сенсоры</h4>
	</a>
	Радиочастотный приемник и датчики EDT SmartSense полностью интегрированы с EDT F1 и SmartLog 5 IVD для отображения данных датчика в режиме реального времени. Облачное приложение EDT WorldFleetLog предоставляет подробные и сводные отчеты об активности датчиков.
	<a href="http://www.e-drivetech.com/products/RF-Sensors">
			<br />	Далее...
			</a>
</div>


	<div class="clear"></div>



<div class="imglist">

	
	<a href="http://www.e-drivetech.com/products/Digital-Video-Recorder">
		<h4>Решения для мобильных видеорегистраторов и видеорегистраторов</h4>
	</a>
	Линейка продуктов EDT для видеорегистраторов и видеорегистраторов EDT является последним дополнением к набору решений EDT для управления автопарком, топливом и активами. Решения EDT DVR полностью интегрированы с WorldFleetLog. Это позволяет управляющим автопарком и активами иметь прямой доступ к видео в реальном времени с каждого транспортного средства или ресурса, перечисленных в WorldFleetLog.
	<a href="http://www.e-drivetech.com/products/Digital-Video-Recorder">
			<br />	Далее...
			</a>
</div>




<div class="imglist">

	
	<a href="http://www.e-drivetech.com/products/SmartSight-S1-Dashcam">
		<h4>Регистратор SmartSight S1</h4>
	</a>
	80% дорожно-транспортных происшествий связаны с отвлечением водителя
	Уровень аварийности торгового флота достигает 20%
	Отвлеченное вождение можно предотвратить
	<a href="http://www.e-drivetech.com/products/SmartSight-S1-Dashcam">
			<br />	Далее...
			</a>
</div>




	<br /><div class="doclinkimgtitle">Это ссылка</div>
	<div class="doclinkimg">
	<img src="/EDT/images/link.gif" alt="WorldFleetLog" align="middle" />
	<a href="/products/worldfleetlog" target="_self" title="WorldFleetLog" >WorldFleetLog</a>
	</div>

</div>

<div id="rightcol">
	
	&nbsp;
</div>


</div>
</div>

@endsection

resources/views/products/index.blade.php
@extends('layouts.inner')

@section('links')
	
	@foreach ($list as $item)
		<a href="/product/{{ $item->id }}">{{ $item->name }}</a>
	@endforeach

@endsection('links')

@section('main')

<div id="centercol">
	<div class="breadcrumbs"><a href='/EDT/index.asp'>Главная</a>&nbsp;&#187;&nbsp;Продукты EDT</div>


	<h1>Продукты EDT</h1>
	<h2>Продукты и решения EDT обеспечивают превосходную производительность FMS ваших клиентов, подкрепленную непревзойденной поддержкой клиентов.</h2>

	@foreach ($list as $item)

		<div class="imglist">

			<a href="http://www.e-drivetech.com/products/worldfleetlog">
				<h4>{{ $item->name }}</h4>
			</a>
			{{ $item->brief }}
			
			<br />	
			<a href="/product/{{ $item->id }}">
				Далее...
			</a>
		</div>
		
	@endforeach

</div>
	
@endsection('main')